spring:
  application:
    name: reto
  main:
    web-application-type: ${SPRING_MAIN_WEB_APPLICATION_TYPE:REACTIVE}
  properties:
    db_table: ${DYNAMODB_TABLE:orders-table-dev}
    db_region: ${DYNAMODB_REGION:us-east-1}