spring:
  application:
    name: reto
  main:
    web-application-type: ${SPRING_MAIN_WEB_APPLICATION_TYPE}
  properties:
    db_table: ${DYNAMODB_TABLE}
    db_region: ${DYNAMODB_REGION}


aws:
  dynamodb.endpoint-override: http://localhost:8000
  # Credenciales "dummy" para el cliente local (no las valida)
  access-key-id: fakeAccessKey
  secret-access-key: fakeSecretKey

