name: Despliegue de API Serverless de Pedidos

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STAGE: dev

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Configurar Java
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Compilar el JAR
      - name: Compilar Java con Maven
        run: mvn clean package -DskipTests

      # 4. Configurar las credenciales de AWS (para poder hacer deploy)
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Instalar Serveless Framework
      - name: Instalar Serverless Framework
        run: npm install -g serverless@4

      # 6. Despliegue con Serverless Framework
      - name: Desplegar Serverless Stack
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_LICENSE }}
        run: serverless deploy --stage dev