name: Despliegue de API Serverless de Pedidos

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Si la rama es 'main', despliega a 'prod'. Podr√≠as usar otra rama para 'dev'.
    env:
      STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Configurar Java
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Compilar el JAR
      - name: Compilar Java con Maven
        run: mvn clean package -DskipTests

      # 6. Despliegue con Serverless Framework
      - name: Desplegar Serverless Stack
        run: |
          npm install -g serverless
          serverless deploy --stage ${STAGE}